# Required: HACS integration (https://hacs.xyz/)
# Required: lovelace-mushroom (https://github.com/piitaya/lovelace-mushroom)
# Required: numberbox-card (https://github.com/junkfix/numberbox-card)
# Required: stack-in-card (https://github.com/custom-cards/stack-in-card)

type: vertical-stack
cards:
  - type: custom:stack-in-card
    mode: vertical
    cards:
      - type: markdown
        content: >-
          ## ğŸ“ Ladningsprocent ved billig strÃ¸m

          <details> <summary><b>LÃ¦s mere</b></summary>


          - **Normal billig strÃ¸m**: Hvis strÃ¸mprisen er under den laveste
          gennemsnitspris per dÃ¸gn i den seneste periode, lades batteriet op til
          "**{{
          states.input_number.ev_very_cheap_grid_charging_max_battery_level.name
          }}**".

          - **Ekstra billig strÃ¸m**: Hvis strÃ¸mprisen er yderligere 25%
          billigere, lades batteriet op til "**{{
          states.input_number.ev_ultra_cheap_grid_charging_max_battery_level.name
          }}**".

          - "**{{ states.input_boolean.ev_fill_up.name }}**" skal vÃ¦re aktiveret

          </details>
      - type: custom:numberbox-card
        border: false
        entity: input_number.ev_very_cheap_grid_charging_max_battery_level
      - type: custom:numberbox-card
        border: false
        entity: input_number.ev_ultra_cheap_grid_charging_max_battery_level
view_layout:
  position: sidebar
