# Replace <PREFIX> with the filename of the script (default is "ev")
# Replace <EV_BATTERY_LEVEL> with the entity_id of the ev battery level sensor or emulated entity_id from this script.

type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: custom:mushroom-entity-card
        entity: input_boolean.<PREFIX>_fill_up
        double_tap_action:
          action: none
        hold_action:
          action: none
        tap_action:
          action: toggle
        secondary_info: none
      - type: custom:mushroom-entity-card
        border: true
        entity: input_number.<PREFIX>_typical_daily_distance
        step: 5
        min: 0
        max: 500
  - type: markdown
    content: |-
      # ğŸ“ {{ states.input_boolean.<PREFIX>_fill_up.name }}

      **Kan aktiveres ved ferie** (Ignorerer arbejdsplanen) ğŸ–ï¸

      <details>
      <summary><b>LÃ¦s mere</b></summary>

      - **ğŸ“Š Opladning**: Fordeles over en uge.
      - **ğŸ”‹ Opladningsbehov**:
        - {{ states.input_number.<PREFIX>_max_recommended_charge_limit_battery_level.state | int - states.<EV_BATTERY_LEVEL>.state | int }}% opdeles i 3 dele.
        - Opladningsbehovet er baseret pÃ¥ forskellen mellem det nuvÃ¦rende batteriniveau og det maksimalt anbefalede.
      - **ğŸ“… Opladningsplan**: Finder de billigste tidspunkter for opladning.
      
      </details>
  - type: custom:mushroom-title-card
    title: ""
