# Required: HACS integration (https://hacs.xyz/)
# Required: lovelace-mushroom (https://github.com/piitaya/lovelace-mushroom)
# Required: numberbox-card (https://github.com/junkfix/numberbox-card)
# Required: stack-in-card (https://github.com/custom-cards/stack-in-card)

type: vertical-stack
cards:
  - type: custom:stack-in-card
    mode: vertical
    cards:
      - type: markdown
        content: >-
          ## ğŸ“ Batteriniveau- og Forvarmningsindstillinger for Elbil


          <details>

          <summary><b>LÃ¦s mere</b></summary>


          - **{{ states.input_number.ev_min_daily_battery_level.name }}**
            - Minimum batteriniveau ved hjemkomst fra arbejde.
          - **{{ states.input_number.ev_min_trip_battery_level.name }}**
            - Minimum batteriniveau ved hjemkomst fra en tur.
          - **{{ states.input_number.ev_min_charge_limit_battery_level.name }}**
            - Bilens minimum mulige opladningsindstilling.
          - **{{
          states.input_number.ev_max_recommended_charge_limit_battery_level.name
          }}**
            - Bilproducentens maksimale anbefaling eller maksimal opladningsprocent ved brug af "Cable Juice Planner".
          - **{{ states.input_number.ev_preheat_minutes_before.name }}**
            - Forvarm bilen fÃ¸r afgang til arbejde og ture.

          </details>
      - type: custom:numberbox-card
        border: false
        entity: input_number.ev_min_daily_battery_level
      - type: custom:numberbox-card
        border: false
        entity: input_number.ev_min_trip_battery_level
      - type: custom:numberbox-card
        border: false
        entity: input_number.ev_min_charge_limit_battery_level
      - type: custom:numberbox-card
        border: false
        entity: input_number.ev_max_recommended_charge_limit_battery_level
      - type: custom:numberbox-card
        border: false
        entity: input_number.ev_preheat_minutes_before
view_layout:
  position: sidebar
