# Replace <PREFIX> with the filename of the script (default is "ev")

type: vertical-stack
cards:
  - type: markdown
    content: >-
      ## ğŸ“ Ladningsprocent ved billig strÃ¸m


      - **Normal billig strÃ¸m**: Hvis strÃ¸mprisen er under den laveste
      gennemsnitspris per dÃ¸gn i den seneste periode, lades batteriet op til
      "**{{
      states.input_number.<PREFIX>_very_cheap_grid_charging_max_battery_level.name
      }}**".


      - **Ekstra billig strÃ¸m**: Hvis strÃ¸mprisen er yderligere 25% billigere,
      lades batteriet op til "**{{
      states.input_number.<PREFIX>_ultra_cheap_grid_charging_max_battery_level.name
      }}**".


      - "**{{ states.input_boolean.<PREFIX>_fill_up.name }}**" skal vÃ¦re aktiveret
  - type: custom:numberbox-card
    border: false
    entity: input_number.<PREFIX>_very_cheap_grid_charging_max_battery_level
  - type: custom:numberbox-card
    border: false
    entity: input_number.<PREFIX>_ultra_cheap_grid_charging_max_battery_level
  - type: custom:mushroom-title-card
    title: ''
view_layout:
  position: sidebar
