# Replace <PREFIX> with the filename of the script (default is "ev")

type: vertical-stack
cards:
  - type: custom:mushroom-entity-card
    entity: input_boolean.<PREFIX>_solar_charging
    double_tap_action:
      action: none
    hold_action:
      action: none
    tap_action:
      action: toggle
    secondary_info: none
  - type: markdown
    content: |
      # ğŸ“ï¸ {{ states.input_boolean.<PREFIX>_solar_charging.name }}

      **Aktiveres nÃ¥r der er overproduktion fra solceller**

      <details>
      <summary><b>LÃ¦s mere</b></summary>

      - **ğŸ“Š Opladning**: Udnytter overskydende solenergi til opladning.
      - **ğŸ”‹ Opladningsbehov**:
        - Tilpasses efter solcelleoverproduktion i forhold til husets forbrug.
        - Maksimal opladning: {{ states.input_number.<PREFIX>_max_recommended_charge_limit_battery_level.state | int }}%
      - **ğŸ“… Opladningsplan**:
        - Estimerer tilgÃ¦ngelig solcelleoverproduktion i lÃ¸bet af ugen under planlÃ¦gningen af "Optimal Ugeopladning" og "Arbejdsplan Opladning"
        - PlanlÃ¦gger opladning ud fra solcelleoverproduktionen, sÃ¥ bilen oplades mest muligt med vedvarende energi.
        
      </details>
  - type: custom:mushroom-title-card
    title: ''
